name: deploy_reduction_ffmpeg_in_ec2

on:
  push:
    branches:
      - 'sriharsha/reduction-ffmpeg-shell-scripts'
env:
  AWS_REGION : ${{ secrets.AWS_REGION }}
# permission can be added at job level or workflow level
permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
       role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
       role-session-name: ${{ secrets.SAMPLE_ROLE_SESSION }}
       aws-region: ${{ env.AWS_REGION }}
  
    - name: deploy ffmpeg_resolution_downsampler
      run: |
        sudo apt-get -y install expect-dev
        unbuffer aws ssm start-session \
        --document-name 'AWS-StartNonInteractiveCommand' \
        --parameters '{"command": ["ls /home/ssm-user"]}' \
        --target ${{ secrets.INSTANCE_ID }}
        
        aws ssm send-command \
        --document-name "AWS-RunShellScript" \
        --instance-ids "${{ secrets.INSTANCE_ID }}" \
        --max-concurrency "1" --max-errors "1" \
        --parameters '{"commands": ["#!/bin/bash","cd /home/ssm-user","ls","curl -o /home/ssm-user/setup_and_run_ffmpeg_resolution_downsampler.sh https://raw.githubusercontent.com/DISHDevEx/leto/sriharsha/reduction-ffmpeg-shell-scripts/reduction/ffmpeg_resolution_downsampler/setup_and_run_ffmpeg_resolution_downsampler.sh",
        "chmod +x "/home/ssm-user/setup_and_run_ffmpeg_resolution_downsampler.sh","pwd","ls"]}'