#GitHub workflow to deploy the Leto - Reduction/Reconstruction modules in the target AWS EC2 instance
#Version: v1.0.0
#
name: deploy-leto-modules-in-ec2

on:
  workflow_dispatch:
    #Inputs for workflow
    inputs:
      instance_id:
        # Description to be shown in the UI
        description: Enter EC2 instance id
        #Instance id entry is mandatory
        required: true
        type: string
      git_branch:
        # Description to be shown in the UI
        description: Enter Git branch name
        #Branch name entry is not mandatory
        required: false
        type: string
        default: main
      module_type:
        # Description to be shown in the UI
        description: Select module type
        #Module type selection is mandatory
        required: true
        type: choice
        options:
            - Reduction
            - Reconstruction
      module:
        # Description to be shown in the UI
        description: Enter reconstruction module name
        #Module name entry is mandatory
        required: true
        type: string
      library_required:
        # Description to be shown in the UI
        description: Select library required
        #Library selection is mandatory
        required: true
        type: choice
        default: None
        options:
            - None
            - Tensorflow
            - PyTorch

env:
  AWS_REGION : ${{ secrets.AWS_REGION }}
#Permission for fetching an OpenId Connect (OIDC) token
permissions:
    id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
       role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
       role-session-name: ${{ secrets.SAMPLE_ROLE_SESSION }}
       aws-region: ${{ env.AWS_REGION }}
    #Download deployment shell script from github to '/home/ec2-user' path in target AWS EC2 instance
    - name: Download deployment script from github to EC2 instance
      run: |
        sudo apt-get -y install expect-dev
        unbuffer aws ssm start-session \
        --document-name 'AWS-StartNonInteractiveCommand' \
        --parameters '{"command": ["sudo curl -o deploy-leto-modules-in-ec2.sh https://raw.githubusercontent.com/DISHDevEx/leto/sriharsha/common-workflow/deployment_scripts/deploy-leto-modules-in-ec2.sh"]}' \
        --target ${{ github.event.inputs.instance_id }}

    - name: Checking parameters being passed to the shell script
      run: |
        echo ${{ github.event.inputs.git_branch }}
        echo ${{ github.event.inputs.module_type }}
        echo ${{ github.event.inputs.module }}
        echo ${{ github.event.inputs.library_required }}
        
    #Execute shell script to deploy module in target AWS EC2 instance
    - name: Deploy module in EC2 instance
      run: |
        unbuffer aws ssm start-session \
        --document-name 'AWS-StartNonInteractiveCommand' \
        --parameters '{"command": ["bash /home/ec2-user/deploy-leto-modules-in-ec2.sh ${{ github.event.inputs.git_branch }} ${{ github.event.inputs.module_type }} ${{ github.event.inputs.module }} ${{ github.event.inputs.library_required }}"]}' \
        --target ${{ github.event.inputs.instance_id }}