#GitHub workflow to deploy the Leto - Reduction modules in the target AWS EC2 instance
#Version: v1.0.0
#
name: deploy-reduction-modules-in-ec2

on:
  workflow_dispatch:
    #Inputs for workflow
    inputs:
      module:
        # Description to be shown in the UI
        description: Reduction module
        #Input selection is mandatory
        required: true
        type: choice
        options:
          - Select module name
          - cv2_jpg_reduction
          - ffmpeg_resolution_downsampler
          - fps_bitrate
env:
  AWS_REGION : ${{ secrets.AWS_REGION }}
#Permission for fetching an OpenId Connect (OIDC) token
permissions:
    id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
       role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
       role-session-name: ${{ secrets.SAMPLE_ROLE_SESSION }}
       aws-region: ${{ env.AWS_REGION }}
    #Download deployment shell script from github to '/home/ssm-user' path in target AWS EC2 instance
    - name: Download deployment script from github to EC2 instance
      run: |
        sudo apt-get -y install expect-dev
        unbuffer aws ssm start-session \
        --document-name 'AWS-StartNonInteractiveCommand' \
        --parameters '{"command": ["curl -o /home/ssm-user/deploy-reduction-modules-in-ec2.sh https://raw.githubusercontent.com/DISHDevEx/leto/sriharsha/reduction-deployment/reduction/deploy-reduction-modules-in-ec2.sh"]}' \
        --target ${{ secrets.REDUCTION_INSTANCE_ID }}

    #Execute shell script to deploy module in target AWS EC2 instance
    - name: Deploy module in EC2 instance
      run: |
        unbuffer aws ssm start-session \
        --document-name 'AWS-StartNonInteractiveCommand' \
        --parameters '{"command": ["bash /home/ssm-user/deploy-reduction-modules-in-ec2.sh ${{ github.event.inputs.module }} | tee /home/ssm-user/deploy-reduction-modules-in-ec2.log"]}' \
        --target ${{ secrets.INSTANCE_ID }}