name: deploy_reduction_ffmpeg_in_ec2

on:
  push:
    branches:
      - 'sriharsha/reduction-ffmpeg-shell-scripts'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: read secrets from AWS Secrets Manager into environment variables 
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secrets: EC2_INSTANCE_ID

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
        role-session-name: samplerolesession
        aws-region: ${{ secrets.AWS_REGION }}

    - name: deploy ffmpeg_resolution_downsampler
      run: |
        aws ssm start-session --target ${{ env.EC2_INSTANCE_ID }}
        cd $HOME
        curl -o setup_and_run_ffmpeg_resolution_downsampler.sh https://raw.githubusercontent.com/DISHDevEx/leto/sriharsha/reduction-ffmpeg-shell-scripts/reduction/ffmpeg_resolution_downsampler/setup_and_run_ffmpeg_resolution_downsampler.sh
        chmod +x ./setup_and_run_ffmpeg_resolution_downsampler.sh
        ls