name: deploy_reduction_ffmpeg_in_ec2

on:
  push:
    branches:
      - 'sriharsha/reduction-ffmpeg-shell-scripts'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::064047601590:role/GitHub_Action_Role
        aws-secret-access-key: 6nfVHE1OBeh9WQu4z4V0eeskjNfbBY7IfVtcnfGv
        role-session-name: samplerolesession
        aws-region: us-east-1
  
    - name: read secrets from AWS Secrets Manager into environment variables 
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: EC2_INSTANCE_ID

    - name: deploy ffmpeg_resolution_downsampler
      run: |
        aws ssm start-session --target ${{ env.EC2_INSTANCE_ID }}
        cd $HOME
        curl -o setup_and_run_ffmpeg_resolution_downsampler.sh https://raw.githubusercontent.com/DISHDevEx/leto/sriharsha/reduction-ffmpeg-shell-scripts/reduction/ffmpeg_resolution_downsampler/setup_and_run_ffmpeg_resolution_downsampler.sh
        chmod +x ./setup_and_run_ffmpeg_resolution_downsampler.sh
        ls