#GitHub workflow to run the Leto - Python scripts in the target AWS EC2 instance
#Version: v2.0.0
#
name: run-python-scripts-in-ec2

on:
  workflow_dispatch:
    #Inputs for workflow
    inputs:
      instance_id:
        # Description to be shown in the UI
        description: Enter EC2 instance id
        #Instance id entry is mandatory
        required: true
        type: string
      library_required:
        # Description to be shown in the UI
        description: Select library required
        #Library selection is mandatory
        required: true
        type: choice
        default: None
        options:
          - None
          - Tensorflow
          - PyTorch
      python_file_path:
        # Description to be shown in the UI
        description: Enter python file path in leto repository
        #Python file path entry is mandatory and the file path should be based on it's location in the leto repository
        #Example: The file path of 'cv2_jpg_reduction.py' in 'leto' repository is, 'reduction/cv2_jpg_reduction/cv2_jpg_reduction.py'
        required: true
        type: string

env:
  AWS_REGION : ${{ secrets.AWS_REGION }}
#Permission for fetching an OpenId Connect (OIDC) token
permissions:
    id-token: write

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
       role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
       role-session-name: ${{ secrets.SAMPLE_ROLE_SESSION }}
       aws-region: ${{ env.AWS_REGION }}
    #Run python file in target AWS EC2 instance
    - name: Download shell script from github to EC2 instance
      run: |
        sudo apt-get -y install expect-dev
        unbuffer aws ssm start-session \
        --document-name 'AWS-StartNonInteractiveCommand' \
        --parameters '{"command": ["curl -o /home/ec2-user/run-python-scripts-in-ec2.sh https://raw.githubusercontent.com/DISHDevEx/leto/main/deployment_scripts/run-python-scripts-in-ec2.sh"]}' \
        --target ${{ github.event.inputs.instance_id }}

    - name: Checking parameters being passed to the shell script
      run: |
        echo ${{ github.event.inputs.library_required }}  
        echo ${{ github.event.inputs.python_file_path }}

    - name: Run python script in EC2 instance using shell script
      run: |
        unbuffer aws ssm start-session \
        --document-name 'AWS-StartNonInteractiveCommand' \
        --parameters '{"command": ["bash /home/ec2-user/run-python-scripts-in-ec2.sh ${{ github.event.inputs.library_required }} ${{ github.event.inputs.python_file_path }} "]}' \
        --target ${{ github.event.inputs.instance_id }}