#GitHub workflow to run the Leto - Python scripts in the target AWS EC2 instance
#Version: v1.0.0
#
name: run-python-scripts-in-ec2

on:
  workflow_dispatch:
    #Inputs for workflow
    inputs:
      instance_id:
        # Description to be shown in the UI
        description: Enter EC2 instance id
        #Instance id entry is mandatory
        required: true
        type: string
      python_file_path:
        # Description to be shown in the UI
        description: Enter python file path in leto repository
        #Python file path entry is mandatory and the file path should be based on it's location in the leto repository
        #Example: The file path of 'cv2_jpg_reduction.py' in 'leto' repository is, 'reduction/cv2_jpg_reduction/cv2_jpg_reduction.py'
        required: true
        type: string

env:
  AWS_REGION : ${{ secrets.AWS_REGION }}
#Permission for fetching an OpenId Connect (OIDC) token
permissions:
    id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
       role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
       role-session-name: ${{ secrets.SAMPLE_ROLE_SESSION }}
       aws-region: ${{ env.AWS_REGION }}
    #Run python file in target AWS EC2 instance
    - name: Run python file in EC2 instance
      run: |
        # sudo apt-get -y install expect-dev
        # unbuffer aws ssm start-session \
        # --document-name 'AWS-StartNonInteractiveCommand' \
        # --parameters '{"command": ["runuser -l ec2-user -c 'python3 /home/ec2-user/leto/${{ github.event.inputs.python_file_path }}'"]}' \
        # --target ${{ github.event.inputs.instance_id }}
        aws ssm send-command \
        --document-name "AWS-RunShellScript" \
        --instance-ids "${{ github.event.inputs.instance_id }}" \
        --max-concurrency "1" --max-errors "1" \
        --parameters '{"commands": ["python3 /home/ec2-user/leto/${{ github.event.inputs.python_file_path }}"]}'